#zsh profile. 

autoload -U colors && colors
TERM=xterm-256color

#Set Colors.
BLUE="%F{33}"
BLACK="%{$fg[default]%}"

#Set PS1-Prompt
PS1="["$BLUE"zsh"$BLACK"]%n@%m %3~> "

#Parsing of general .profile for all POSIX compliant shells.
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'
