#zsh profile. 

autoload -U colors && colors

#PS1 and Colors.
BLUE="%F{33}"
BLACK="%{$fg[default]%}"
PS1="["$BLUE"zsh"$BLACK"]%n@%m %3~> "

export TERM=xterm-256color

autoload -Uz compinit
compinit -i
autoload -U select-word-style
select-word-style bash

#Auto-Completions
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi
#autoload _kubectl

#History settings
HISTSIZE=1000
SAVEHIST=$HISTSIZE
HISTFILE=$HOME/.zsh_history

#Parsing of general .profile for all POSIX compliant shells.
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'
