setopt complete_in_word
#setopt single_line_zle
setopt INC_APPEND_HISTORY
setopt hist_ignore_all_dups
setopt BANG_HIST
setopt extended_glob
setopt AUTO_MENU

autoload -U compinit
if [ -f $HOME/.zcompdump  ]; then
compinit -d $HOME/.zcompdump -i
else
compinit -i
fi
autoload -U select-word-style
select-word-style bash

#Auto-Completions
if [ -e $commands[kubectl] ]; then
#if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi
#autoload _kubectl
