setopt complete_in_word
#setopt single_line_zle
setopt INC_APPEND_HISTORY
setopt hist_ignore_all_dups
setopt BANG_HIST
setopt extendedglob
#setopt AUTO_MENU

autoload -Uz compinit
compinit -i
autoload -U select-word-style
select-word-style bash

#Auto-Completions
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi
#autoload _kubectl